[project]
name = "vgapui"
version = "0.1"

# [project.scripts]
# dict = "app.entry_points:dict"
# primer = "app.entry_points:primer"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

